apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: hello_flux_test
  namespace: hello_flux_test
  labels:
    app: hello_flux_test
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 50%
      maxSurge: 1
  template:
    metadata:
      labels:
        app: hello_flux_test
    spec:
      serviceAccountName: default
      containers:
        - name: hello_flux_test
          image: quay.io/cookiec/hello_flux_test:master-3de47e54
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
          resources:
            limits:
              cpu: 10m
              memory: 30Mi
            requests:
              cpu: 10m
              memory: 30Mi
      terminationGracePeriodSeconds: 30