apiVersion: v1
kind: Service
metadata:
  name: hello_flux-service
  namespace: hello_flux_test
spec:
  selector:
    app: hello_flux_test
  type: NodePort
  ports:
    - name: http
      port: 80
      targetPort: 80
      nodePort: 30036
      protocol: TCP